---
- name: Collect baseline data from all servers
  hosts: all
  gather_facts: yes
  roles:
    - baseline_collect

# ------------------------------------------------------------------------------

- name: Build and send combined report
  hosts: localhost
  run_once: true
  roles:
    - email_report
  vars:
    all_results: "{{ hostvars }}"
