package_state: latest

email_to: "receiver_email@example.com"
email_from: "sender-email@example.com"

smtp_username: "{{ lookup('env', 'SMTP_USER') }}"
smtp_password: "{{ lookup('env', 'SMTP_PASS') }}"


