package_state: latest

email_to: "lrfrancisco17@gmail.com"
email_from: "lrfranciscol17labs@gmail.com"

smtp_username: "{{ lookup('env', 'SMTP_USER') }}"
smtp_password: "{{ lookup('env', 'SMTP_PASS') }}"


