---
- name: Render combined HTML report
  template:
    src: combined_report.j2
    dest: /tmp/combined_report.html

- name: Send combined email
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    to: "{{ email_to }}"
    from: "{{ email_from }}"
    subject: "Combined Baseline Report"
    subtype: html
    body: "{{ lookup('file', '/tmp/combined_report.html') }}"
